# Generated by Django 5.1.1 on 2024-10-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('responsavel', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('total_itens', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo', models.CharField(max_length=50)),
                ('codigo_barra', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('custo_unidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.CharField(blank=True, max_length=255, null=True)),
                ('saida', models.CharField(blank=True, max_length=255, null=True)),
                ('analise_rapida', models.TextField(blank=True, null=True)),
                ('recomendacoes', models.CharField(blank=True, max_length=255, null=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
