# Generated by Django 5.1.1 on 2024-10-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0003_remove_relatorio_analise_rapida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=255)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='ItemRelatorio',
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
