# Generated by Django 5.1.1 on 2024-10-22 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0004_funcionario_delete_itemrelatorio_delete_relatorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id_fornecedor', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nome_fornecedor', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('endereco', models.TextField()),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='nome_funcionario',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='id',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nomeprod', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('cod_barra', models.CharField(max_length=50, unique=True)),
                ('quant', models.IntegerField()),
                ('validade', models.DateTimeField()),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inovare.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id_relatorio', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('data_relat', models.DateTimeField(auto_now_add=True)),
                ('resumo', models.TextField()),
                ('total_itens', models.IntegerField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entrada', models.IntegerField()),
                ('saida', models.IntegerField()),
                ('analise_rapida', models.BooleanField(default=False)),
                ('recomendacoes', models.TextField(blank=True)),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inovare.funcionario')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-data_relat'],
            },
        ),
    ]
