# Generated by Django 5.1.1 on 2024-10-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0005_fornecedor_alter_funcionario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='id_fornecedor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id_produto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='id_relatorio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
