# Generated by Django 5.1.1 on 2024-10-22 14:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0006_alter_fornecedor_id_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
