# Generated by Django 5.1.1 on 2024-10-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0007_alter_funcionario_id_funcionario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fornecedor',
            new_name='Fornecedor_2',
        ),
        migrations.RenameModel(
            old_name='Funcionario',
            new_name='Funcionario_2',
        ),
        migrations.RenameModel(
            old_name='Produtos',
            new_name='Produtos_2',
        ),
        migrations.RenameModel(
            old_name='Relatorio',
            new_name='Relatorio_2',
        ),
        migrations.AlterModelOptions(
            name='fornecedor_2',
            options={'verbose_name': 'Fornecedor_2', 'verbose_name_plural': 'Fornecedores_2'},
        ),
        migrations.AlterModelOptions(
            name='funcionario_2',
            options={'verbose_name': 'Funcionário_2', 'verbose_name_plural': 'Funcionários_2'},
        ),
        migrations.AlterModelOptions(
            name='produtos_2',
            options={'verbose_name': 'Produto_2', 'verbose_name_plural': 'Produtos_2'},
        ),
        migrations.AlterModelOptions(
            name='relatorio_2',
            options={'ordering': ['-data_relat'], 'verbose_name': 'Relatório_2', 'verbose_name_plural': 'Relatórios_2'},
        ),
    ]
