# Generated by Django 5.1.1 on 2024-10-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0009_alter_funcionario_2_id_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos_2',
            name='cod_barra',
            field=models.UUIDField(unique=True),
        ),
    ]
