# Generated by Django 5.1.1 on 2024-10-22 16:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0010_alter_produtos_2_cod_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos_2',
            name='cod_barra',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
