# Generated by Django 5.1.1 on 2024-10-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0011_alter_produtos_2_cod_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos_2',
            name='validade',
            field=models.DateTimeField(blank=True),
        ),
    ]
