# Generated by Django 5.1.1 on 2024-10-22 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0012_alter_produtos_2_validade'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio_2',
            name='produto',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Inovare.produtos_2'),
        ),
    ]
