# Generated by Django 5.1.1 on 2024-11-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inovare', '0014_alter_produtos_2_cod_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio_2',
            name='entrada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio_2',
            name='saida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
